=== eawag-surface-waters-research/Delft3D/test/deltares_testbench/configs/xsd/deltaresTestbench_v3-2.00.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2014 rel. 2 sp1 (http://www.altova.com) by Afdeling ICT (Stichting Deltares) -->
<!-- W3C Schema generated by XMLSpy v2014 rel. 2 sp1 (http://www.altova.com) -->
<xs:schema xmlns="http://schemas.deltares.nl/deltaresTestbench_v3" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xerces="http://xerces.apache.org" targetNamespace="http://schemas.deltares.nl/deltaresTestbench_v3">
    <xs:element name="file" type="T_File"/>
    <xs:element name="from" type="xs:string"/>
    <xs:element name="path" type="xs:string"/>
    <xs:element name="root" type="xs:string"/>
    <xs:element name="shell" type="T_Shell"/>
    <xs:element name="checks" type="T_Checks"/>
    <xs:element name="config" type="T_Config"/>
    <xs:element name="program" type="T_Program"/>
    <xs:element name="argument" type="xs:string"/>
    <xs:element name="location" type="T_Location"/>
    <xs:element name="password" type="xs:string"/>
    <xs:element name="programs" type="T_Programs"/>
    <xs:element name="testCase" type="T_TestCase"/>
    <xs:element name="username" type="xs:string"/>
    <xs:element name="arguments" type="T_Arguments"/>
    <xs:element name="locations" type="T_Locations"/>
    <xs:element name="testCases" type="T_TestCases"/>
    <xs:element name="credential" type="T_Credential"/>
    <xs:element name="enginesDir" type="xs:string"/>
    <xs:element name="localPaths" type="T_LocalPaths"/>
    <xs:element name="maxRunTime" type="T_MaxRunTime"/>
    <xs:element name="credentials" type="T_Credentials"/>
    <xs:element name="referenceDir" type="xs:string"/>
    <xs:element name="testCasesDir" type="xs:string"/>
    <xs:element name="defaultTestCases" type="T_DefaultTestCases"/>
    <xs:element name="deltaresTestbench_v3" type="T_DeltaresTestbench_v3"/>
    <xs:element name="module" type="xs:string"/>
    <xs:element name="modules" type="T_Modules"/>
    <xs:element name="environment" type="T_Environment"/>
    <xs:element name="environments" type="T_Environments"/>
    <xs:element name="parameter" type="T_Parameter"/>
    <xs:element name="parameters" type="T_Parameters"/>
    <xs:element name="skipline" type="xs:string"/>
    <xs:element name="workingDirectory" type="xs:string"/>
    <xs:complexType name="T_MaxRunTime">
        <xs:simpleContent>
            <xs:extension base="xs:decimal">
                <xs:attribute name="OverruleRefMaxRunTime" type="xs:boolean"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="T_File">
        <xs:choice>
            <xs:sequence minOccurs="0">
                <xs:element ref="parameters" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="skipline"/>
            </xs:sequence>
        </xs:choice>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="type" type="xs:string" use="required"/>
        <xs:attribute name="ignore" type="xs:boolean" use="optional" default="false"/>
    </xs:complexType>
    <xs:complexType name="T_Shell">
        <xs:attribute name="ref" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="T_Checks">
        <xs:sequence>
            <xs:element ref="file" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="T_Config">
        <xs:all>
            <xs:element ref="credentials" minOccurs="0" maxOccurs="1"/>
            <xs:element ref="localPaths"/>
            <xs:element ref="locations"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="T_Program">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element ref="path" minOccurs="0"/>
            <xs:element ref="workingDirectory" minOccurs="0"/>
            <xs:element ref="arguments" minOccurs="0"/>
            <xs:element ref="shell" minOccurs="0"/>
            <xs:element ref="location" minOccurs="0"/>
            <xs:element ref="modules" minOccurs="0"/>
            <xs:element ref="environments" minOccurs="0"/>
        </xs:choice>
        <xs:attribute name="ref" type="xs:string" use="optional"/>
        <xs:attribute name="name" type="xs:string"/>
        <xs:attribute name="ignoreReturnValue" type="xs:boolean"/>
        <xs:attribute name="logOutputToFile" type="xs:boolean"/>
        <xs:attribute name="programStringRemoveQuotes" type="xs:boolean"/>
        <xs:attribute name="ignoreStandardError" type="xs:boolean"/>
        <xs:attribute name="addSearchPaths" type="xs:boolean"/>
        <xs:attribute name="shellStringRemoveQuotes" type="xs:boolean"/>
        <xs:attribute name="storeOutput" type="xs:boolean"/>
        <xs:attribute name="seq" type="xs:positiveInteger"/>
        <xs:attribute name="delay" type="xs:decimal"/>
    </xs:complexType>
    <xs:complexType name="T_Location">
        <xs:choice>
            <xs:sequence>
                <xs:element ref="credential" minOccurs="0"/>
                <xs:element ref="root"/>
            </xs:sequence>
            <xs:element ref="from"/>
        </xs:choice>
        <xs:attribute name="ref" type="xs:string" use="optional"/>
        <xs:attribute name="name" type="xs:string" use="optional"/>
        <xs:attribute name="type" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="T_Programs">
        <xs:sequence>
            <xs:element ref="program" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="T_TestCase">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element ref="path" minOccurs="0"/>
            <xs:element ref="programs" minOccurs="0"/>
            <xs:element ref="location" minOccurs="0"/>
            <xs:element ref="maxRunTime" minOccurs="0"/>
            <xs:element ref="checks" minOccurs="0"/>
        </xs:choice>
        <xs:attribute name="ref" use="optional">
            <xs:simpleType>
                <xs:restriction base="xs:string"/>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="name" type="xs:string" use="optional"/>
        <xs:attribute name="ignore" type="xs:boolean" use="optional" default="false"/>
    </xs:complexType>
    <xs:complexType name="T_Arguments">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element ref="argument"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="T_Modules">
        <xs:sequence maxOccurs="unbounded">
            <xs:element ref="module"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="T_Environments">
        <xs:sequence maxOccurs="unbounded">
            <xs:element ref="environment"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="T_Environment">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="name"/>
                <xs:attribute name="type"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="T_Parameters">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element ref="parameter"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="T_Parameter">
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="tolerance" type="xs:double"/>
        <xs:attribute name="toleranceAbsolute" type="xs:double"/>
        <xs:attribute name="toleranceRelative" type="xs:double"/>
        <xs:attribute name="location" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="T_Locations">
        <xs:sequence>
            <xs:element ref="location" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="T_TestCases">
        <xs:sequence>
            <xs:element ref="testCase" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="T_Credential">
        <xs:sequence minOccurs="0" maxOccurs="1">
            <xs:element ref="username"/>
            <xs:element ref="password"/>
        </xs:sequence>
        <xs:attribute name="ref" type="xs:string" use="optional"/>
        <xs:attribute name="name" type="xs:string" use="optional"/>
    </xs:complexType>
    <xs:complexType name="T_LocalPaths">
        <xs:all>
            <xs:element ref="testCasesDir"/>
            <xs:element ref="enginesDir"/>
            <xs:element ref="referenceDir"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="T_Credentials">
        <xs:sequence>
            <xs:element ref="credential"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="T_DefaultTestCases">
        <xs:sequence>
            <xs:element ref="testCase" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="T_DeltaresTestbench_v3">
        <xs:all>
            <xs:element ref="config"/>
            <xs:element ref="programs"/>
            <xs:element ref="defaultTestCases"/>
            <xs:element ref="testCases"/>
        </xs:all>
    </xs:complexType>
</xs:schema>

=== eawag-surface-waters-research/Delft3D/test/deltares_testbench/configs/dimr/dimr_dflowfm_mormerge_win64.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<deltaresTestbench_v3 xmlns="http://schemas.deltares.nl/deltaresTestbench_v3"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns:xi="http://www.w3.org/2001/XInclude"
         xsi:schemaLocation="http://schemas.deltares.nl/deltaresTestbench_v3 http://content.oss.deltares.nl/schemas/deltaresTestbench_v3-2.00.xsd">
    <config>
        <localPaths>
            <testCasesDir>./data/cases</testCasesDir>
            <enginesDir>./data/engines</enginesDir>
            <referenceDir>./data/reference_results</referenceDir>
        </localPaths>
        <locations>
            <location name="reference_results">
                <credential ref="commandline"/>
                <root>https://repos.deltares.nl/repos/DSCTestbench/trunk/references</root>
            </location>
            <location name="cases">
                <credential ref="commandline"/>
                <root>https://repos.deltares.nl/repos/DSCTestbench/trunk/cases</root>
            </location>
            <location name="reference_engines">
                <credential ref="commandline"/>
                <root>https://repos.deltares.nl/repos/DSCTestbench/trunk/references/bin</root>
            </location>
            <location name="engines_to_compare">
                <credential ref="commandline"/>
                <root>https://repos.deltares.nl/repos/DSCTestbench/trunk/references</root>
            </location>
            <location name="local">
                <root>./data/engines</root>
            </location>
        </locations>
    </config>
  <programs>
    <program name="command_prompt" addSearchPaths="false">
      <path>cmd</path>
      <arguments>
        <argument>/C</argument>
      </arguments>
    </program>
    <program name="svn" addSearchPaths="false">
      <path>thirdparty\svn\win64\svn.exe</path>
    </program>
    <program name="dimr" logOutputToFile="true" programStringRemoveQuotes="true" addSearchPaths="true">
        <path>dimr/bin/dimr.exe</path>
        <shell ref="command_prompt"/>
        <location ref="reference_engines" type="reference">
            <from>win64</from>
        </location>
        <location ref="engines_to_compare" type="check">
            <from>teamcity_artifacts/x64</from>
        </location>
    </program>
    <program name="checkhydbal" addSearchPaths="false">
      <path>thirdparty\checkhydbal\win64\checkhydbal.exe</path>
    </program>
	
    <program name="mormerge" logOutputToFile="true" ignoreStandardError="true" ignoreReturnValue="true" addSearchPaths="true">
	    <path>dmor/scripts/run_mormerge.bat</path>
        <location ref="reference_engines" type="reference">
            <from>win64</from>
        </location>
        <location ref="engines_to_compare" type="check">
            <from>teamcity_artifacts/x64</from>
        </location>
    </program>

  </programs>
  <defaultTestCases>
    <testCase name="dflowfm_default">
    <programs>
        <program ref="dimr">
            <arguments>
                <argument>dimr.xml</argument>
                <argument>&gt;dimr_screen.log 2&gt;&amp;1</argument>
            </arguments>
        </program>
    </programs>
      <location ref="cases" type="input">
        <!-- if "to" is not specified, "from" is used as target -->
        <from>.</from>
      </location>
      <location ref="reference_results" type="reference">
        <from>win64</from>
      </location>
      <maxRunTime>3600.0</maxRunTime>
      <!-- seconds -->
    </testCase>
    <testCase name="dflowfm_config">
    <programs>
        <program ref="dimr">
            <arguments>
                <argument>dimr_config.xml</argument>
                <argument>&gt;dimr_screen.log 2&gt;&amp;1</argument>
            </arguments>
        </program>
    </programs>
      <location ref="cases" type="input">
        <!-- if "to" is not specified, "from" is used as target -->
        <from>.</from>
      </location>
      <location ref="reference_results" type="reference">
        <from>win64</from>
      </location>
      <maxRunTime>3600.0</maxRunTime>
      <!-- seconds -->
    </testCase>
    <testCase name="platform_specific">
    <programs>
        <program ref="dimr">
            <arguments>
                <argument>dimr.xml</argument>
                <argument>&gt;dimr_screen.log 2&gt;&amp;1</argument>
            </arguments>
        </program>
    </programs>
      <location ref="cases" type="input">
        <!-- if "to" is not specified, "from" is used as target -->
        <from>.</from>
      </location>
      <location ref="reference_results" type="reference">
        <from>win64</from>
      </location>
      <maxRunTime>3600.0</maxRunTime>
      <!-- seconds -->
    </testCase>
  </defaultTestCases>
  <!--
  testCases
  -->

<testCases>
    <testCase name="e123_f01_c01_trench_VanRijn1993_mormerge_e02_f22_c01" ref="dflowfm_default">
        <path>e123_dflowfm-mormerge/f01_general/c01_trench_VanRijn1993_mormerge_e02_f22_c01</path>
        <maxRunTime>600.0000000</maxRunTime>
        <programs>
            <program ref="mormerge">
                <workingDirectory>merge</workingDirectory>
                <arguments>
                    <argument>trench_windows.mm</argument>
                </arguments>
            </program>
        </programs>
        <checks>
            <file name="strong/dflowfmoutput/test_his.nc" type="netCDF">
                <parameters>
                    <parameter name="waterlevel" toleranceAbsolute="0.1"/>
                    <parameter name="bedlevel"   toleranceAbsolute="0.1"/>
                </parameters>
            </file>
            <file name="weak/dflowfmoutput/test_his.nc" type="netCDF">
                <parameters>
                    <parameter name="waterlevel" toleranceAbsolute="0.1"/>
                    <parameter name="bedlevel"   toleranceAbsolute="0.1"/>
                </parameters>
            </file>
            <file name="strong/dflowfmoutput/test_map.nc" type="netCDF">
                <parameters>
                    <parameter name="mesh2d_s1"     toleranceAbsolute="0.1"/>
                    <parameter name="mesh2d_u1"     toleranceAbsolute="0.1"/>
					<parameter name="mesh2d_mor_bl" toleranceAbsolute="0.1"/>
                </parameters>
            </file>
            <file name="weak/dflowfmoutput/test_map.nc" type="netCDF">
                <parameters>
                    <parameter name="mesh2d_s1"     toleranceAbsolute="0.1"/>
                    <parameter name="mesh2d_u1"     toleranceAbsolute="0.1"/>
					<parameter name="mesh2d_mor_bl" toleranceAbsolute="0.1"/>
                </parameters>
            </file>
        </checks>
    </testCase>

    <testCase name="e123_f02_c01_trench_VanRijn1993_mormerge_e02_f22_c01" ref="dflowfm_default">
        <path>e123_dflowfm-mormerge/f02_mergedtuser/c01_trench_VanRijn1993_mormerge_e02_f22_c01</path>
        <maxRunTime>600.0000000</maxRunTime>
        <programs>
            <program ref="mormerge">
				<workingDirectory>merge</workingDirectory>
				<arguments>
					<argument>trench_windows.mm</argument>
				</arguments>
			</program>
		</programs>
		<checks>
			<file name="strong/dflowfmoutput/test_his.nc" type="netCDF">
				<parameters>
					<parameter name="waterlevel" toleranceAbsolute="0.1"/>
					<parameter name="bedlevel"   toleranceAbsolute="0.1"/>
				</parameters>
			</file>
			<file name="weak/dflowfmoutput/test_his.nc" type="netCDF">
				<parameters>
					<parameter name="waterlevel" toleranceAbsolute="0.1"/>
					<parameter name="bedlevel"   toleranceAbsolute="0.1"/>
				</parameters>
			</file>
			<file name="strong/dflowfmoutput/test_map.nc" type="netCDF">
				<parameters>
					<parameter name="mesh2d_s1"     toleranceAbsolute="0.1"/>
					<parameter name="mesh2d_u1"     toleranceAbsolute="0.1"/>
					<parameter name="mesh2d_mor_bl" toleranceAbsolute="0.1"/>
				</parameters>
			</file>
			<file name="weak/dflowfmoutput/test_map.nc" type="netCDF">
				<parameters>
					<parameter name="mesh2d_s1"     toleranceAbsolute="0.1"/>
					<parameter name="mesh2d_u1"     toleranceAbsolute="0.1"/>
					<parameter name="mesh2d_mor_bl" toleranceAbsolute="0.1"/>
				</parameters>
			</file>
		</checks>
	</testCase>

</testCases>
</deltaresTestbench_v3>

=== eawag-surface-waters-research/Delft3D/test/deltares_testbench/configs/dimr/dimr_dpart_lnx64.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<deltaresTestbench_v3 xmlns="http://schemas.deltares.nl/deltaresTestbench_v3"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xmlns:xi="http://www.w3.org/2001/XInclude"
		xsi:schemaLocation="http://schemas.deltares.nl/deltaresTestbench_v3 http://content.oss.deltares.nl/schemas/deltaresTestbench_v3-2.00.xsd">
				<!--
				Basic Linux   configuration file: tb3_cfg_lnx64.xml
				Basic Windows configuration file: tb3_cfg_win64.xml
				-->
	<config>
		<localPaths>
			<testCasesDir>./data/cases</testCasesDir>
			<enginesDir>./data/engines</enginesDir>
			<referenceDir>./data/references</referenceDir>
		</localPaths>
		<locations>
			<location name="p-opt-engines">
				<credential ref="commandline"/>
				<root>/f/h4/opt</root>
			</location>
			<location name="testbench_v1-engines">
				<credential ref="commandline"/>
				<root>./data/engines</root>
			</location>
			<location name="dsctestbench-cases">
				<credential ref="commandline"/>
				<root>https://repos.deltares.nl/repos/DSCTestbench/trunk/cases</root>
			</location>
			<location name="dsctestbench-references">
				<credential ref="commandline"/>
				<root>https://repos.deltares.nl/repos/DSCTestbench/trunk/references</root>
			</location>
			<location name="network-references">
				<root>./data/engines</root>
			</location>
			<location name="local">
				<root>./data/engines</root>
			</location>
		</locations>
	</config>
				<!--
				Programs
				
				Optional attributes:
					ignoreStandardError="true"       default: false
					ignoreReturnValue="true"         default: false
					logOutputToFile="true"           default: true
					programStringRemoveQuotes="true" default: false
						Needed by WAQ1: -p "proc_def" does NOT work
										-p proc_def   does work
					shellStringRemoveQuotes="true"   default: false
						Needed by mpi: mpirun -n 3 "program program_args" does NOT work
									   mpirun -n 3 program programargs    does work
					storeOutput="true"               default: false
						Needed by esm_create: The result must be passed through to setenv(DIO_SHM_ESM)/esm_delete
						Before using this attribute, ALL program-output was stored. This caused problems on Linux.
				
				Path:
					The path to the executable is build as follows:
						<networkpath_root>/<from>path
					To local:
						<networkpath>/<from>
						is copied to
						<localPaths_enginesDir>/<to>
						where "<to>" is by default the same value of "<from>"
						When "<version" is defined, "_<version>" is added.
					Example:
						if:
						<networpath_root>        = /f/h4/opt
						<from> = <to>            = swan/lnx64
						<path>                   = bin/swan.exe
						<llocalPaths_enginesDir> = /tmp
						then:
						copyRecursive /f/h4/opt/swan/lnx64 /tmp/swan/lnx64
						all subdirs of /tmp/swan/lnx64 are added to the searchPaths automatically
				
				Environment parameters:
					type path:
						"." resolves to <localPaths_enginesDir>/<to>                (in example above: /tmp/swan/lnx64)
						example:
						<environment name="D3D_HOME" type="path">../.</environment> (in example above: /tmp/swan)
					type raw:
						just the value
						example:
						<environment name="ARCH" type="raw">lnx64</environment>
				-->
	<programs>
		<!--
		The order is important. Start with the following programs:
			command_prompt
			svn
			mpi
		-->
		<program name="command_prompt">
			<path>/bin/bash</path>
			<arguments>
				<argument>-c</argument>
			</arguments>
		</program>
		<program name="svn">
			<path>svn</path>
			<environments>
				<environment name="LD_LIBRARY_PATH" type="path">/opt/subversion/lib</environment>
			</environments>
		</program>
		<!---
		<program name="mpi" shellStringRemoveQuotes="true" addSearchPaths="true" excludeSearchPathsContaining="share/delft3d/esmf">
			<path>mpiexec</path>
			<arguments>
 				<argument>-n 2</argument>
			</arguments>
			<modules>
				<module>intel/18.0.3</module>
				<module>mpich/3.3.2_intel18.0.3</module>
			</modules>
		</program>
		-->
		<program name="vs" ignoreStandardError="true" ignoreReturnValue="true" addSearchPaths="true" excludeSearchPathsContaining="share/delft3d/esmf">
			<shell ref="command_prompt"/>
			<path>thirdparty/vs/lnx64/vs</path>
			<environments>
				<environment name="PAGER" type="raw">more</environment>
			</environments>
		</program>

		<program name="PART" logOutputToFile="true" addSearchPaths="true" excludeSearchPathsContaining="share/delft3d/esmf">
			<location ref="dsctestbench-references" type="reference">
				<from>bin/delft3d_open_source/lnx64</from>
			</location>
			<location ref="local" type="check">
				<from>teamcity_artifacts/lnx64</from>
			</location>
			<path>bin/run_dpart.sh</path>
		</program>
	</programs>
				<!--
				default testCases
				
				Testcases may refer to a default testCase with the attribute
				ref="name_of_default_testcase"
				-->
	<defaultTestCases>
		<testCase name="part_default">
			<location ref="dsctestbench-cases" type="input">
				<!-- if "to" is not specified, "from" is used as target -->
				<from>.</from>
			</location>
			<location ref="dsctestbench-references" type="reference">
				<from>lnx64</from>
			</location>
			<maxRunTime>3600.0</maxRunTime> <!-- seconds -->
		</testCase>
	</defaultTestCases>
				<!--
				testCases
				
				Optional attributes:
					maxRunTime: OverruleRefMaxRunTime="true" default: false
									if false: maxRunTime in this config.xml file is     overruled by the maxRunTime of the reference run
									if true : maxRunTime in this config.xml file is NOT overruled by the maxRunTime of the reference run
				
				Special replacements:
				[output(progname)]		: Will be replaced by the output of (the last run of) program "progname"
										  Used by esm_create (Linux)
				[programpath(progname)] : Will be replaced by the path to the program named "progname"
										  Used by WAQ1 to refer to the proc_def file
				
				Checks:
					<file name="dat-file" type="NEFIS">
						<parameters name="groupname">
							<parameter name="quantity" toleranceAbsolute="real_value">
					<file name="nc-file" type="netCDF">
						<parameters>                                        (name not needed)
							<parameter name="quantity" toleranceAbsolute="real_value">
					<file name="filnam" type="ASCII"/>      (parameters/parameter not needed)
					Optional attribute:
						ignore="true" Don't bother when this file is in the reference dir but absent in the check dir
				
				-->
	<!--
	testCases
	-->
	<xi:include href="../include/dpart_all_cases.xml"/>
</deltaresTestbench_v3>
