=== eawag-surface-waters-research/Delft3D/test/deltares_testbench/configs/xsd/deltaresTestbench_v3-2.00.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2014 rel. 2 sp1 (http://www.altova.com) by Afdeling ICT (Stichting Deltares) -->
<!-- W3C Schema generated by XMLSpy v2014 rel. 2 sp1 (http://www.altova.com) -->
<xs:schema xmlns="http://schemas.deltares.nl/deltaresTestbench_v3" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xerces="http://xerces.apache.org" targetNamespace="http://schemas.deltares.nl/deltaresTestbench_v3">
    <xs:element name="file" type="T_File"/>
    <xs:element name="from" type="xs:string"/>
    <xs:element name="path" type="xs:string"/>
    <xs:element name="root" type="xs:string"/>
    <xs:element name="shell" type="T_Shell"/>
    <xs:element name="checks" type="T_Checks"/>
    <xs:element name="config" type="T_Config"/>
    <xs:element name="program" type="T_Program"/>
    <xs:element name="argument" type="xs:string"/>
    <xs:element name="location" type="T_Location"/>
    <xs:element name="password" type="xs:string"/>
    <xs:element name="programs" type="T_Programs"/>
    <xs:element name="testCase" type="T_TestCase"/>
    <xs:element name="username" type="xs:string"/>
    <xs:element name="arguments" type="T_Arguments"/>
    <xs:element name="locations" type="T_Locations"/>
    <xs:element name="testCases" type="T_TestCases"/>
    <xs:element name="credential" type="T_Credential"/>
    <xs:element name="enginesDir" type="xs:string"/>
    <xs:element name="localPaths" type="T_LocalPaths"/>
    <xs:element name="maxRunTime" type="T_MaxRunTime"/>
    <xs:element name="credentials" type="T_Credentials"/>
    <xs:element name="referenceDir" type="xs:string"/>
    <xs:element name="testCasesDir" type="xs:string"/>
    <xs:element name="defaultTestCases" type="T_DefaultTestCases"/>
    <xs:element name="deltaresTestbench_v3" type="T_DeltaresTestbench_v3"/>
    <xs:element name="module" type="xs:string"/>
    <xs:element name="modules" type="T_Modules"/>
    <xs:element name="environment" type="T_Environment"/>
    <xs:element name="environments" type="T_Environments"/>
    <xs:element name="parameter" type="T_Parameter"/>
    <xs:element name="parameters" type="T_Parameters"/>
    <xs:element name="skipline" type="xs:string"/>
    <xs:element name="workingDirectory" type="xs:string"/>
    <xs:complexType name="T_MaxRunTime">
        <xs:simpleContent>
            <xs:extension base="xs:decimal">
                <xs:attribute name="OverruleRefMaxRunTime" type="xs:boolean"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="T_File">
        <xs:choice>
            <xs:sequence minOccurs="0">
                <xs:element ref="parameters" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="skipline"/>
            </xs:sequence>
        </xs:choice>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="type" type="xs:string" use="required"/>
        <xs:attribute name="ignore" type="xs:boolean" use="optional" default="false"/>
    </xs:complexType>
    <xs:complexType name="T_Shell">
        <xs:attribute name="ref" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="T_Checks">
        <xs:sequence>
            <xs:element ref="file" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="T_Config">
        <xs:all>
            <xs:element ref="credentials" minOccurs="0" maxOccurs="1"/>
            <xs:element ref="localPaths"/>
            <xs:element ref="locations"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="T_Program">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element ref="path" minOccurs="0"/>
            <xs:element ref="workingDirectory" minOccurs="0"/>
            <xs:element ref="arguments" minOccurs="0"/>
            <xs:element ref="shell" minOccurs="0"/>
            <xs:element ref="location" minOccurs="0"/>
            <xs:element ref="modules" minOccurs="0"/>
            <xs:element ref="environments" minOccurs="0"/>
        </xs:choice>
        <xs:attribute name="ref" type="xs:string" use="optional"/>
        <xs:attribute name="name" type="xs:string"/>
        <xs:attribute name="ignoreReturnValue" type="xs:boolean"/>
        <xs:attribute name="logOutputToFile" type="xs:boolean"/>
        <xs:attribute name="programStringRemoveQuotes" type="xs:boolean"/>
        <xs:attribute name="ignoreStandardError" type="xs:boolean"/>
        <xs:attribute name="addSearchPaths" type="xs:boolean"/>
        <xs:attribute name="shellStringRemoveQuotes" type="xs:boolean"/>
        <xs:attribute name="storeOutput" type="xs:boolean"/>
        <xs:attribute name="seq" type="xs:positiveInteger"/>
        <xs:attribute name="delay" type="xs:decimal"/>
    </xs:complexType>
    <xs:complexType name="T_Location">
        <xs:choice>
            <xs:sequence>
                <xs:element ref="credential" minOccurs="0"/>
                <xs:element ref="root"/>
            </xs:sequence>
            <xs:element ref="from"/>
        </xs:choice>
        <xs:attribute name="ref" type="xs:string" use="optional"/>
        <xs:attribute name="name" type="xs:string" use="optional"/>
        <xs:attribute name="type" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="T_Programs">
        <xs:sequence>
            <xs:element ref="program" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="T_TestCase">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element ref="path" minOccurs="0"/>
            <xs:element ref="programs" minOccurs="0"/>
            <xs:element ref="location" minOccurs="0"/>
            <xs:element ref="maxRunTime" minOccurs="0"/>
            <xs:element ref="checks" minOccurs="0"/>
        </xs:choice>
        <xs:attribute name="ref" use="optional">
            <xs:simpleType>
                <xs:restriction base="xs:string"/>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="name" type="xs:string" use="optional"/>
        <xs:attribute name="ignore" type="xs:boolean" use="optional" default="false"/>
    </xs:complexType>
    <xs:complexType name="T_Arguments">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element ref="argument"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="T_Modules">
        <xs:sequence maxOccurs="unbounded">
            <xs:element ref="module"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="T_Environments">
        <xs:sequence maxOccurs="unbounded">
            <xs:element ref="environment"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="T_Environment">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="name"/>
                <xs:attribute name="type"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="T_Parameters">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element ref="parameter"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="T_Parameter">
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="tolerance" type="xs:double"/>
        <xs:attribute name="toleranceAbsolute" type="xs:double"/>
        <xs:attribute name="toleranceRelative" type="xs:double"/>
        <xs:attribute name="location" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="T_Locations">
        <xs:sequence>
            <xs:element ref="location" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="T_TestCases">
        <xs:sequence>
            <xs:element ref="testCase" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="T_Credential">
        <xs:sequence minOccurs="0" maxOccurs="1">
            <xs:element ref="username"/>
            <xs:element ref="password"/>
        </xs:sequence>
        <xs:attribute name="ref" type="xs:string" use="optional"/>
        <xs:attribute name="name" type="xs:string" use="optional"/>
    </xs:complexType>
    <xs:complexType name="T_LocalPaths">
        <xs:all>
            <xs:element ref="testCasesDir"/>
            <xs:element ref="enginesDir"/>
            <xs:element ref="referenceDir"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="T_Credentials">
        <xs:sequence>
            <xs:element ref="credential"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="T_DefaultTestCases">
        <xs:sequence>
            <xs:element ref="testCase" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="T_DeltaresTestbench_v3">
        <xs:all>
            <xs:element ref="config"/>
            <xs:element ref="programs"/>
            <xs:element ref="defaultTestCases"/>
            <xs:element ref="testCases"/>
        </xs:all>
    </xs:complexType>
</xs:schema>

=== eawag-surface-waters-research/Delft3D/test/deltares_testbench/configs/skillbed_dflowfm_wave_mor_win64.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<deltaresTestbench_v3 xmlns="http://schemas.deltares.nl/deltaresTestbench_v3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://schemas.deltares.nl/deltaresTestbench_v3 http://content.oss.deltares.nl/schemas/deltaresTestbench_v3-2.00.xsd">
    <!--
    Basic Configuration file
    -->
    <config>
        <localPaths>
            <testCasesDir>./data/cases</testCasesDir>
            <enginesDir>./data/engines</enginesDir>
            <referenceDir>./data/reference_results</referenceDir>
        </localPaths>
        <locations>
            <location name="reference_engines">
                <credential ref="commandline"/>
                <root>https://repos.deltares.nl/repos/DSCTestbench/trunk/references</root>
            </location>
            <location name="reference_results">
                <credential ref="commandline"/>
                <root>https://repos.deltares.nl/repos/DSCTestbench/trunk/cases</root>
            </location>
            <location name="cases">
                <credential ref="commandline"/>
                <root>https://repos.deltares.nl/repos/DSCTestbench/trunk/cases/</root>
            </location>
            <location name="engines_to_compare">
                <root>./data/engines</root>
            </location>
        </locations>
    </config>
    <!--
    Programs
    -->
    <programs>
        <!--
        The order is important. Start with the following programs:
            command_prompt
            svn
            mpi
        -->
        <program name="command_prompt">
            <path>cmd</path>
            <arguments>
                <argument>/C</argument>
            </arguments>
        </program>
        <program name="PYTHON">
            <shell ref="command_prompt"/>
            <path>python.exe</path>
        </program>
        <program name="svn">
            <path>thirdparty/svn/win64/svn.exe</path>
        </program>
        <program name="dimr" logOutputToFile="true" programStringRemoveQuotes="true">
            <path>dimr/scripts/run_dimr.bat</path>
            <shell ref="command_prompt"/>
            <location ref="reference_engines" type="reference">
                <from>x64</from>
            </location>
            <location ref="engines_to_compare" type="check">
                <from>teamcity_artifacts/x64</from>
            </location>
        </program>
    </programs>
    <!--
    default testCases
    -->
    <defaultTestCases>
        <testCase name="skillbed_default">
            <programs>
                <program ref="dimr"/>
            </programs>
            <location ref="reference_results" type="reference">
                <from>.</from>
            </location>
            <location ref="cases" type="input">
                <from>.</from>
            </location>
            <maxRunTime>60.0</maxRunTime> <!-- seconds -->
        </testCase>
    </defaultTestCases>
    <!--
    testCases
    -->
    <testCases>
        <!-- ======================================================================== -->
        <testCase name="e200_f01_c02_egmond" ref="skillbed_default" ignore="true">
            <path>e200_skillbed/f01_flowfm_wave/c02_egmond</path>
            <programs>
                <program ref="dimr" seq="1" >
                    <arguments>
                        <argument>dimr_config.xml &gt;dimr.log 2&gt;&amp;1</argument>
                    </arguments>
                </program>                
                <program ref="PYTHON" seq="2" >
                    <arguments>
                        <argument>postprocessing/scripts/post_processing.py &gt;post_processing.log 2&gt;&amp;1</argument>
                    </arguments>
                </program>                
                <program ref="PYTHON" seq="3" >
                    <arguments>
                        <argument>scripts/generate_latex_doc/generate_latex_doc.py --texfile doc/casedoc.tex &gt;casedoc.log 2&gt;&amp;1</argument>
                    </arguments>
                </program>                
            </programs>
            <maxRunTime>14400.0</maxRunTime> <!-- seconds -->
        </testCase>
        <!-- ======================================================================== -->
        <testCase name="e200_f02_c01_straight_coast_breakwater" ref="skillbed_default" ignore="true">
            <path>e200_skillbed/f02_flowfm_wave_mor_vs_d3d4/c01_straight_coast_breakwater</path>
            <programs>
                <program ref="dimr" seq="1" >
                    <arguments>
                        <argument>dimr_config.xml &gt;dimr.log 2&gt;&amp;1</argument>
                    </arguments>
                </program>                
                <program ref="PYTHON" seq="2">
                    <arguments>
                        <argument>postprocessing/scripts/post_processing.py &gt;post_processing.log 2&gt;&amp;1</argument>
                    </arguments>
                </program>                
                <program ref="PYTHON" seq="3">
                    <arguments>
                        <argument>scripts/generate_latex_doc/generate_latex_doc.py --texfile doc/casedoc.tex &gt;casedoc.log 2&gt;&amp;1</argument>
                    </arguments>
                </program>                
            </programs>
            <maxRunTime>14400.0</maxRunTime> <!-- seconds -->
        </testCase>
        <!-- ======================================================================== -->
        <testCase name="e200_f02_c02_zandmotor_first_year" ref="skillbed_default" ignore="true">
            <path>e200_skillbed/f02_flowfm_wave_mor_vs_d3d4/c02_zandmotor_first_year</path>
            <programs>
                <program ref="dimr" seq="1" >
                    <arguments>
                        <argument>dimr_config.xml &gt;dimr.log 2&gt;&amp;1</argument>
                    </arguments>
                </program>                
                <program ref="PYTHON" seq="2">
                    <arguments>
                        <argument>postprocessing/scripts/post_processing.py &gt;post_processing.log 2&gt;&amp;1</argument>
                    </arguments>
                </program>                
                <program ref="PYTHON" seq="3">
                    <arguments>
                        <argument>scripts/generate_latex_doc/generate_latex_doc.py --texfile doc/casedoc.tex &gt;casedoc.log 2&gt;&amp;1</argument>
                    </arguments>
                </program>                
            </programs>
            <maxRunTime>14400.0</maxRunTime> <!-- seconds -->
        </testCase>
        <!-- ======================================================================== -->
        <testCase name="e200_f02_c06_avalanching" ref="skillbed_default" ignore="false">
            <path>e200_skillbed/f02_flowfm_wave_mor_vs_d3d4/c06_avalanching</path>
            <programs>
                <program ref="dimr" seq="1" >
                    <arguments>
                        <argument>dimr_config.xml &gt;dimr.log 2&gt;&amp;1</argument>
                    </arguments>
                </program>                
                <program ref="PYTHON" seq="2">
                    <arguments>
                        <argument>postprocessing/scripts/post_processing.py &gt;post_processing.log 2&gt;&amp;1</argument>
                    </arguments>
                </program>                
                <program ref="PYTHON" seq="3">
                    <arguments>
                        <argument>scripts/generate_latex_doc/generate_latex_doc.py --texfile doc/casedoc.tex &gt;casedoc.log 2&gt;&amp;1</argument>
                    </arguments>
                </program>                
            </programs>
            <maxRunTime>14400.0</maxRunTime> <!-- seconds -->
        </testCase>
    </testCases>
</deltaresTestbench_v3>

=== eawag-surface-waters-research/Delft3D/test/deltares_testbench/configs/dimr/dimr_dflowfm_waq_coupling_aggregation_lnx64.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<deltaresTestbench_v3 xmlns="http://schemas.deltares.nl/deltaresTestbench_v3"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xi="http://www.w3.org/2001/XInclude"
    xsi:schemaLocation="http://schemas.deltares.nl/deltaresTestbench_v3 http://content.oss.deltares.nl/schemas/deltaresTestbench_v3-2.00.xsd">
  <config>
    <localPaths>
      <testCasesDir>./data/cases</testCasesDir>
      <enginesDir>./data/engines</enginesDir>
      <referenceDir>./data/references</referenceDir>
    </localPaths>
    <locations>
      <location name="dsctestbench-cases">
        <credential ref="commandline" />
        <root>https://repos.deltares.nl/repos/DSCTestbench/trunk/cases</root>
      </location>
      <location name="dsctestbench-references">
        <credential ref="commandline" />
        <root>https://repos.deltares.nl/repos/DSCTestbench/trunk/references</root>
      </location>
      <location name="reference_engines">
        <credential ref="commandline"/>
        <root>https://repos.deltares.nl/repos/DSCTestbench/trunk/references/bin</root>
        </location>
      <location name="local">
        <root>./data/engines</root>
      </location>
    </locations>
  </config>
      <!--
    Programs
    -->
    <programs>
        <!--
        The order is important. Start with the following programs:
            command_prompt
            svn
            mpi
        -->
        <program name="command_prompt">
            <path>/bin/bash</path>
            <arguments>
                <argument>-c</argument>
            </arguments>
        </program>
        <program name="svn">
            <path>svn</path>
            <environments>
                <environment name="LD_LIBRARY_PATH" type="path">/opt/subversion/lib</environment>
            </environments>
        </program>
        <program name="dimr" logOutputToFile="true" programStringRemoveQuotes="true" addSearchPaths="true" excludeSearchPathsContaining="share/delft3d/esmf">
            <location ref="reference_engines" type="reference">
                <from>lnx64</from>
            </location>
            <location ref="local" type="check">
                <from>teamcity_artifacts/lnx64</from> <!-- just the first part of the directory structure, wil be file by TeamCity -->
            </location>
            <path>bin/run_dimr.sh</path>
            <environments>
                <environment name="OMP_NUM_THREADS" type="raw">1</environment>
                <environment name="PROC_DEF_DIR" type="path">[programpath(dimr)]/../share/delft3d</environment>
            </environments>
            <arguments>
                <argument>-m dimr.xml</argument>
                <argument>&gt;dimr_screen.log 2&gt;&amp;1</argument>
            </arguments>
        </program>
        <program name="dimr_waq" logOutputToFile="true" programStringRemoveQuotes="true" addSearchPaths="true" excludeSearchPathsContaining="share/delft3d/esmf">
            <location ref="reference_engines" type="reference">
                <from>lnx64</from>
            </location>
            <location ref="local" type="check">
                <from>teamcity_artifacts/lnx64</from> <!-- just the first part of the directory structure, wil be file by TeamCity -->
            </location>
            <path>bin/run_dimr.sh</path>
            <environments>
                <environment name="OMP_NUM_THREADS" type="raw">1</environment>
                <environment name="PROC_DEF_DIR" type="path">[programpath(dimr)]/../share/delft3d</environment>
            </environments>
            <arguments>
                <argument>-m dimr_waq.xml</argument>
                <argument>&gt;dimr_screen.log 2&gt;&amp;1</argument>
            </arguments>
        </program>
        <program name="dimr-mpi" logOutputToFile="true" programStringRemoveQuotes="true" addSearchPaths="true" excludeSearchPathsContaining="share/delft3d/esmf">
            <location ref="reference_engines" type="reference">
                <from>lnx64</from>
            </location>
            <location ref="local" type="check">
                <from>teamcity_artifacts/lnx64</from> <!-- just the first part of the directory structure, wil be file by TeamCity -->
            </location>
            <path>bin/run_dimr.sh</path>
            <environments>
                <environment name="OMP_NUM_THREADS" type="raw">1</environment>
                <environment name="PROC_DEF_DIR" type="path">[programpath(dimr)]/../share/delft3d</environment>
            </environments>
            <arguments>
                <argument>-c 3</argument>
                <argument>-m dimr.xml</argument>
                <!-- <argument>&gt;dimr_screen.log 2&gt;&amp;1</argument> -->
            </arguments>
        </program>
        <program name="vs" ignoreStandardError="true" ignoreReturnValue="true" addSearchPaths="true" excludeSearchPathsContaining="share/delft3d/esmf">
            <shell ref="command_prompt"/>
            <path>thirdparty/vs/lnx64/vs</path>
            <environments>
                <environment name="PAGER" type="raw">more</environment>
            </environments>
        </program>
        <program name="waqmerge" addSearchPaths="false" logOutputToFile="true" >
            <path>data/engines/teamcity_artifacts/lnx64/bin/run_waqmerge.sh</path>
        </program>
        <program name="checkhydbal" addSearchPaths="false" logOutputToFile="true">
            <path>thirdparty/checkhydbal/lnx64/run_checkhydbal.sh</path>
        </program>
        <program name="maptonetcdf" addSearchPaths="false" logOutputToFile="true">
            <path>data/engines/teamcity_artifacts/lnx64/bin/run_maptonetcdf.sh</path>
        </program>
        <program name="poi2asc" addSearchPaths="false" logOutputToFile="true">
            <path>thirdparty/poi2asc/lnx64/run_poi2asc.sh</path>
        </program>
    </programs>
  <defaultTestCases>
    <testCase name="dflowfm_default">
      <location ref="dsctestbench-cases" type="input">
        <!-- if "to" is not specified, "from" is used as target -->
        <from>.</from>
      </location>
      <location ref="dsctestbench-references" type="reference">
        <from>win64</from>
      </location>
      <maxRunTime>3600.0</maxRunTime>
      <!-- seconds -->
    </testCase>
    <testCase name="dflowfm_platform_specific_refs">
      <location ref="dsctestbench-cases" type="input">
        <!-- if "to" is not specified, "from" is used as target -->
        <from>.</from>
      </location>
      <location ref="dsctestbench-references" type="reference">
        <from>lnx64</from>
      </location>
      <maxRunTime>3600.0</maxRunTime>
      <!-- seconds -->
    </testCase>
  </defaultTestCases>
  <!--
  testCases
  -->
  <xi:include href="../include/dimr_dflowfm_waq_coupling_aggregation.xml"/>
</deltaresTestbench_v3>

=== eawag-surface-waters-research/Delft3D/test/deltares_testbench/configs/dimr/dimr_dflowfm_drtc_tutorials_lnx64.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<deltaresTestbench_v3 xmlns="http://schemas.deltares.nl/deltaresTestbench_v3"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns:xi="http://www.w3.org/2001/XInclude"
         xsi:schemaLocation="http://schemas.deltares.nl/deltaresTestbench_v3 http://content.oss.deltares.nl/schemas/deltaresTestbench_v3-2.00.xsd">
    <config>
        <localPaths>
            <testCasesDir>./data/cases</testCasesDir>
            <enginesDir>./data/engines</enginesDir>
            <referenceDir>./data/reference_results</referenceDir>
        </localPaths>
        <locations>
            <location name="reference_results">
                <credential ref="commandline"/>
                <root>https://repos.deltares.nl/repos/DSCTestbench/trunk/references</root>
            </location>
            <location name="reference_engines">
                <credential ref="commandline"/>
                <root>https://repos.deltares.nl/repos/DSCTestbench/trunk/references/bin</root>
            </location>
            <location name="cases">
                <credential ref="commandline"/>
                <root>https://repos.deltares.nl/repos/DSCTestbench/trunk/cases</root>
            </location>
            <location name="engines_to_compare">
                <credential ref="commandline"/>
                <root>./data/engines</root>
            </location>
        </locations>
    </config>
    <programs>
         <program name="command_prompt">
            <path>/bin/bash</path>
            <arguments>
                <argument>-c</argument>
            </arguments>
        </program>
        <program name="svn">
           <path>svn</path>
            <environments>
                <environment name="LD_LIBRARY_PATH" type="path">/opt/subversion/lib</environment>
            </environments>
        </program>
        <program name="dimr" logOutputToFile="true" programStringRemoveQuotes="true">
            <path>bin/run_dimr.sh</path>
            <location ref="reference_engines" type="reference">
                <from>lnx64</from>
            </location>
            <location ref="engines_to_compare" type="check">
                <from>teamcity_artifacts/lnx64</from> <!-- just the first part of the directory structure, wil be file by TeamCity -->
            </location>
        </program>
    </programs>
    <!--
    default testCases
    -->
    <defaultTestCases>
        <testCase name="dimr_trunk">
            <programs>
                <program ref="dimr">
                    <arguments>
                        <argument>-m dimr.xml</argument>
                    </arguments>
                </program>
            </programs>
            <location ref="reference_results" type="reference">
                <from>lnx64</from>
            </location>
            <location ref="cases" type="input">
                <from>.</from>
            </location>
            <maxRunTime>600.0</maxRunTime> <!-- seconds -->
        </testCase>
    </defaultTestCases>
  <!--
  testCases
  -->
  <xi:include href="../include/dimr_dflowfm_drtc_tutorials.xml"/>
</deltaresTestbench_v3>
