=== eawag-surface-waters-research/Delft3D/test/deltares_testbench/configs/xsd/deltaresTestbench_v3-2.00.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2014 rel. 2 sp1 (http://www.altova.com) by Afdeling ICT (Stichting Deltares) -->
<!-- W3C Schema generated by XMLSpy v2014 rel. 2 sp1 (http://www.altova.com) -->
<xs:schema xmlns="http://schemas.deltares.nl/deltaresTestbench_v3" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xerces="http://xerces.apache.org" targetNamespace="http://schemas.deltares.nl/deltaresTestbench_v3">
    <xs:element name="file" type="T_File"/>
    <xs:element name="from" type="xs:string"/>
    <xs:element name="path" type="xs:string"/>
    <xs:element name="root" type="xs:string"/>
    <xs:element name="shell" type="T_Shell"/>
    <xs:element name="checks" type="T_Checks"/>
    <xs:element name="config" type="T_Config"/>
    <xs:element name="program" type="T_Program"/>
    <xs:element name="argument" type="xs:string"/>
    <xs:element name="location" type="T_Location"/>
    <xs:element name="password" type="xs:string"/>
    <xs:element name="programs" type="T_Programs"/>
    <xs:element name="testCase" type="T_TestCase"/>
    <xs:element name="username" type="xs:string"/>
    <xs:element name="arguments" type="T_Arguments"/>
    <xs:element name="locations" type="T_Locations"/>
    <xs:element name="testCases" type="T_TestCases"/>
    <xs:element name="credential" type="T_Credential"/>
    <xs:element name="enginesDir" type="xs:string"/>
    <xs:element name="localPaths" type="T_LocalPaths"/>
    <xs:element name="maxRunTime" type="T_MaxRunTime"/>
    <xs:element name="credentials" type="T_Credentials"/>
    <xs:element name="referenceDir" type="xs:string"/>
    <xs:element name="testCasesDir" type="xs:string"/>
    <xs:element name="defaultTestCases" type="T_DefaultTestCases"/>
    <xs:element name="deltaresTestbench_v3" type="T_DeltaresTestbench_v3"/>
    <xs:element name="module" type="xs:string"/>
    <xs:element name="modules" type="T_Modules"/>
    <xs:element name="environment" type="T_Environment"/>
    <xs:element name="environments" type="T_Environments"/>
    <xs:element name="parameter" type="T_Parameter"/>
    <xs:element name="parameters" type="T_Parameters"/>
    <xs:element name="skipline" type="xs:string"/>
    <xs:element name="workingDirectory" type="xs:string"/>
    <xs:complexType name="T_MaxRunTime">
        <xs:simpleContent>
            <xs:extension base="xs:decimal">
                <xs:attribute name="OverruleRefMaxRunTime" type="xs:boolean"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="T_File">
        <xs:choice>
            <xs:sequence minOccurs="0">
                <xs:element ref="parameters" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="skipline"/>
            </xs:sequence>
        </xs:choice>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="type" type="xs:string" use="required"/>
        <xs:attribute name="ignore" type="xs:boolean" use="optional" default="false"/>
    </xs:complexType>
    <xs:complexType name="T_Shell">
        <xs:attribute name="ref" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="T_Checks">
        <xs:sequence>
            <xs:element ref="file" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="T_Config">
        <xs:all>
            <xs:element ref="credentials" minOccurs="0" maxOccurs="1"/>
            <xs:element ref="localPaths"/>
            <xs:element ref="locations"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="T_Program">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element ref="path" minOccurs="0"/>
            <xs:element ref="workingDirectory" minOccurs="0"/>
            <xs:element ref="arguments" minOccurs="0"/>
            <xs:element ref="shell" minOccurs="0"/>
            <xs:element ref="location" minOccurs="0"/>
            <xs:element ref="modules" minOccurs="0"/>
            <xs:element ref="environments" minOccurs="0"/>
        </xs:choice>
        <xs:attribute name="ref" type="xs:string" use="optional"/>
        <xs:attribute name="name" type="xs:string"/>
        <xs:attribute name="ignoreReturnValue" type="xs:boolean"/>
        <xs:attribute name="logOutputToFile" type="xs:boolean"/>
        <xs:attribute name="programStringRemoveQuotes" type="xs:boolean"/>
        <xs:attribute name="ignoreStandardError" type="xs:boolean"/>
        <xs:attribute name="addSearchPaths" type="xs:boolean"/>
        <xs:attribute name="shellStringRemoveQuotes" type="xs:boolean"/>
        <xs:attribute name="storeOutput" type="xs:boolean"/>
        <xs:attribute name="seq" type="xs:positiveInteger"/>
        <xs:attribute name="delay" type="xs:decimal"/>
    </xs:complexType>
    <xs:complexType name="T_Location">
        <xs:choice>
            <xs:sequence>
                <xs:element ref="credential" minOccurs="0"/>
                <xs:element ref="root"/>
            </xs:sequence>
            <xs:element ref="from"/>
        </xs:choice>
        <xs:attribute name="ref" type="xs:string" use="optional"/>
        <xs:attribute name="name" type="xs:string" use="optional"/>
        <xs:attribute name="type" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="T_Programs">
        <xs:sequence>
            <xs:element ref="program" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="T_TestCase">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element ref="path" minOccurs="0"/>
            <xs:element ref="programs" minOccurs="0"/>
            <xs:element ref="location" minOccurs="0"/>
            <xs:element ref="maxRunTime" minOccurs="0"/>
            <xs:element ref="checks" minOccurs="0"/>
        </xs:choice>
        <xs:attribute name="ref" use="optional">
            <xs:simpleType>
                <xs:restriction base="xs:string"/>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="name" type="xs:string" use="optional"/>
        <xs:attribute name="ignore" type="xs:boolean" use="optional" default="false"/>
    </xs:complexType>
    <xs:complexType name="T_Arguments">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element ref="argument"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="T_Modules">
        <xs:sequence maxOccurs="unbounded">
            <xs:element ref="module"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="T_Environments">
        <xs:sequence maxOccurs="unbounded">
            <xs:element ref="environment"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="T_Environment">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="name"/>
                <xs:attribute name="type"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="T_Parameters">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element ref="parameter"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="T_Parameter">
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="tolerance" type="xs:double"/>
        <xs:attribute name="toleranceAbsolute" type="xs:double"/>
        <xs:attribute name="toleranceRelative" type="xs:double"/>
        <xs:attribute name="location" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="T_Locations">
        <xs:sequence>
            <xs:element ref="location" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="T_TestCases">
        <xs:sequence>
            <xs:element ref="testCase" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="T_Credential">
        <xs:sequence minOccurs="0" maxOccurs="1">
            <xs:element ref="username"/>
            <xs:element ref="password"/>
        </xs:sequence>
        <xs:attribute name="ref" type="xs:string" use="optional"/>
        <xs:attribute name="name" type="xs:string" use="optional"/>
    </xs:complexType>
    <xs:complexType name="T_LocalPaths">
        <xs:all>
            <xs:element ref="testCasesDir"/>
            <xs:element ref="enginesDir"/>
            <xs:element ref="referenceDir"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="T_Credentials">
        <xs:sequence>
            <xs:element ref="credential"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="T_DefaultTestCases">
        <xs:sequence>
            <xs:element ref="testCase" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="T_DeltaresTestbench_v3">
        <xs:all>
            <xs:element ref="config"/>
            <xs:element ref="programs"/>
            <xs:element ref="defaultTestCases"/>
            <xs:element ref="testCases"/>
        </xs:all>
    </xs:complexType>
</xs:schema>

=== eawag-surface-waters-research/Delft3D/test/deltares_testbench/configs/dimr/dimr_dpart_fm_win64.xml
<?xml version="1.0"	encoding="iso-8859-1"?>
<deltaresTestbench_v3 xmlns="http://schemas.deltares.nl/deltaresTestbench_v3"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xmlns:xi="http://www.w3.org/2001/XInclude"
		xsi:schemaLocation="http://schemas.deltares.nl/deltaresTestbench_v3 http://content.oss.deltares.nl/schemas/deltaresTestbench_v3-2.00.xsd">
				<!--
				Basic Linux	  configuration	file: tb3_cfg_lnx64.xml
				Basic Windows configuration	file: tb3_cfg_win64.xml
				-->
	<config>
		<localPaths>
			<testCasesDir>.\data\cases</testCasesDir>
			<enginesDir>.\data\engines</enginesDir>
			<referenceDir>.\data\references</referenceDir>
		</localPaths>
		<locations>
			<location name="p-opt-engines">
				<credential	ref="commandline"/>
				<root>\\deltapdc.deltares.nl\project\h4\opt</root>
			</location>
			<location name="testbench_v1-engines">
				<credential	ref="commandline"/>
				<root>\\deltapdc.deltares.nl\project\delft3d\test_data</root>
			</location>
			<location name="dsctestbench-cases">
				<credential	ref="commandline"/>
				<root>https://repos.deltares.nl/repos/DSCTestbench/trunk/cases</root>
			</location>
			<location name="dsctestbench-references">
				<credential	ref="commandline"/>
				<root>https://repos.deltares.nl/repos/DSCTestbench/trunk/references</root>
			</location>
			<location name="network-references">
				<root>p:\delft3d\test_data\d3d-flow\flow\versions\6.01.10.4289</root>
			</location>
			<location name="local">
				<root>./data/engines</root>
			</location>
		</locations>
	</config>
				<!--
				Programs

				Optional attributes:
					ignoreStandardError="true"		 default: false
					ignoreReturnValue="true"		 default: false
					logOutputToFile="true"			 default: true
					programStringRemoveQuotes="true" default: false
						Needed by WAQ1:	-p "proc_def" does NOT work
										-p proc_def	  does work
					shellStringRemoveQuotes="true"	 default: false
						Needed by mpi: mpirun -n 3 "program	program_args" does NOT work
									   mpirun -n 3 program programargs	  does work
					storeOutput="true"				 default: false
						Needed by esm_create: The result must be passed	through	to setenv(DIO_SHM_ESM)/esm_delete
						Before using this attribute, ALL program-output	was	stored.	This caused	problems on	Linux.

				Path:
					The	path to	the	executable is build	as follows:
						<networkpath_root>/<from>path
					To local:
						<networkpath>/<from>
						is copied to
						<localPaths_enginesDir>/<to>
						where "<to>" is	by default the same	value of "<from>"
						When "<version"	is defined,	"_<version>" is	added.
					Example:
						if:
						<networpath_root>		 = /f/h4/opt
						<from> = <to>			 = swan/lnx64
						<path>					 = bin/swan.exe
						<llocalPaths_enginesDir> = /tmp
						then:
						copyRecursive /f/h4/opt/swan/lnx64 /tmp/swan/lnx64
						all	subdirs	of /tmp/swan/lnx64 are added to	the	searchPaths	automatically

				Environment	parameters:
					type path:
						"."	resolves to	<localPaths_enginesDir>/<to>				(in	example	above: /tmp/swan/lnx64)
						example:
						<environment name="D3D_HOME" type="path">..\.</environment>	(in	example	above: /tmp/swan)
					type raw:
						just the value
						example:
						<environment name="ARCH" type="raw">lnx64</environment>
				-->
	<programs>
		<!--
		The	order is important.	Start with the following programs:
			command_prompt
			svn
			mpi
		-->
		<program name="command_prompt">
			<path>cmd</path>
			<arguments>
				<argument>/C</argument>
			</arguments>
		</program>
		<program name="svn">
			<path>thirdparty\svn\win64\svn.exe</path>
		</program>
		  <program name="vs">
			<shell ref="command_prompt"/>
			<path>thirdparty\vs\win64\vs.exe</path>
			<environments>
				<environment name="PAGER" type="raw">more</environment>
			</environments>
		</program>

		<program name="PART" logOutputToFile="true"	addSearchPaths="true">
			<location ref="dsctestbench-references"	type="reference">
				<from>bin/delft3d/x64</from>
			</location>
			<location ref="local" type="check">
				<from>teamcity_artifacts/x64</from>
			</location>
			<path>dpart/bin/delpar.exe</path>
		</program>
	</programs>
				<!--
				default	testCases

				Testcases may refer	to a default testCase with the attribute
				ref="name_of_default_testcase"
				-->
	<defaultTestCases>
		<testCase name="part_default">
			<location ref="dsctestbench-cases" type="input">
				<!-- if	"to" is	not	specified, "from" is used as target	-->
				<from>.</from>
			</location>
			<location ref="dsctestbench-references"	type="reference">
				<from>lnx64</from>
			</location>
			<maxRunTime>3600.0</maxRunTime>	<!-- seconds -->
		</testCase>
	</defaultTestCases>
	<!--
	testCases
	-->
	<xi:include href="../include/dpart_all_cases_fm.xml"/>
</deltaresTestbench_v3>

=== eawag-surface-waters-research/Delft3D/test/deltares_testbench/configs/dimr/dimr_dflowfm_win64_rws_acceptance.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<deltaresTestbench_v3 xmlns="http://schemas.deltares.nl/deltaresTestbench_v3"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://schemas.deltares.nl/deltaresTestbench_v3 http://content.oss.deltares.nl/schemas/deltaresTestbench_v3-2.00.xsd">
    <config>
        <localPaths>
            <testCasesDir>./data/cases</testCasesDir>
            <enginesDir>./data/engines</enginesDir>
            <referenceDir>./data/reference_results</referenceDir>
        </localPaths>
        <locations>
            <location name="reference_results">
                <credential ref="commandline"/>
                <root>https://repos.deltares.nl/repos/DSCTestbench/trunk/references</root>
            </location>
            <location name="cases">
                <credential ref="commandline"/>
                <root>https://repos.deltares.nl/repos/DSCTestbench/trunk/cases</root>
            </location>
            <location name="reference_engines">
                <credential ref="commandline"/>
                <root>https://repos.deltares.nl/repos/DSCTestbench/trunk/references/bin</root>
            </location>
            <location name="engines_to_compare">
                <credential ref="commandline"/>
                <root>https://repos.deltares.nl/repos/DSCTestbench/trunk/references</root>
            </location>
            <location name="local">
                <root>./data/engines</root>
            </location>
        </locations>
    </config>
    <!--
    Programs
    -->
    <programs>
        <!--
        The order is important. Start with the following programs:
            command_prompt
            svn
            mpi
        -->
        <program name="command_prompt">
            <path>cmd</path>
            <arguments>
                <argument>/C</argument>
            </arguments>
        </program>
        <program name="svn">
            <path>thirdparty\svn\win64\svn.exe</path>
        </program>
        <program name="dimr" logOutputToFile="true" programStringRemoveQuotes="true" addSearchPaths="true">
            <shell ref="command_prompt"/>
            <location ref="reference_engines" type="reference">
                <from>win64</from>
            </location>
            <location ref="local" type="check">
                <from>teamcity_artifacts/x64</from> <!-- just the first part of the directory structure, wil be file by TeamCity -->
            </location>
            <path>dimr/bin/dimr.exe</path>
            <environments>
                <environment name="D3D_HOME" type="path">[programpath(dimr)]\..\..\..</environment>
                <environment name="ARCH" type="raw">win64</environment>
                <environment name="OMP_NUM_THREADS" type="raw">1</environment>
            </environments>
        </program>
    </programs>
    <!--
    default testCases
    -->
    <defaultTestCases>
        <testCase name="dimr_trunk">
            <programs>
                <program ref="dimr">
                    <arguments>
                        <argument>dimr.xml</argument>
                        <argument>&gt;dimr_screen.log 2&gt;&amp;1</argument>
                    </arguments>
                </program>
            </programs>
            <location ref="reference_results" type="reference">
                <from>win64</from>
            </location>
            <location ref="cases" type="input">
                <from>.</from>
            </location>
            <maxRunTime>60.0</maxRunTime> <!-- seconds -->
        </testCase>
    </defaultTestCases>
    <!--
    testCases
    -->
    <testCases>
        <!-- ======================================================================== -->
        <testCase name="e02_f091_c040_rws_waal" ref="dimr_trunk">
            <path>e02_dflowfm/f091_rws_acceptance/c040_rws_waal</path>
            <maxRunTime>7200.0</maxRunTime> <!-- seconds -->
             <checks>
                <file name="dflowfm/resultaten/Q10165_his.nc" type="NETCDF">
                    <parameters>
                        <parameter name="waterlevel" toleranceAbsolute="0.01" />
                    </parameters>
                </file>
            </checks>              
        </testCase>
        <!-- ======================================================================== -->
    </testCases>
</deltaresTestbench_v3>

=== eawag-surface-waters-research/Delft3D/test/deltares_testbench/configs/dflowfm_unvalidated_win64.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<deltaresTestbench_v3 xmlns="http://schemas.deltares.nl/deltaresTestbench_v3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://schemas.deltares.nl/deltaresTestbench_v3 http://content.oss.deltares.nl/schemas/deltaresTestbench_v3-2.00.xsd">
  <!--
				Basic Linux   configuration file: tb3_cfg_lnx64_hp.xml
				Basic Windows configuration file: tb3_cfg_win32_hp.xml
				From hp to sp      : Replace "config_d_hydro.xml" by "config_d_hydro_sp.xml" (all occurences)
				From hp to parallel: Use mpi as shell (in related program)
									 Overrule maxruntime when needed
									 Only cases that run in parallel mode
				-->
  <config>
    <!-- CRITICAL, ERROR, WARNING, INFO, DEBUG -->
    <localPaths>
      <testCasesDir>.\data\cases</testCasesDir>
      <enginesDir>.\data\engines</enginesDir>
      <referenceDir>.\data\references</referenceDir>
    </localPaths>
    <locations>
      <location name="dsctestbench-cases">
        <credential ref="commandline" />
        <root>https://repos.deltares.nl/repos/DSCTestbench/trunk/cases</root>
      </location>
      <location name="dsctestbench-references">
        <credential ref="commandline" />
        <root>https://repos.deltares.nl/repos/DSCTestbench/trunk/references</root>
      </location>
      <location name="local">
        <root>./data/engines</root>
      </location>
    </locations>
  </config>
  <!--
				Programs
				
				Optional attributes:
					ignoreStandardError="true"       default: false
					ignoreReturnValue="true"         default: false
					logOutputToFile="true"           default: true
					programStringRemoveQuotes="true" default: false
						Needed by WAQ1: -p "proc_def" does NOT work
										-p proc_def   does work
					shellStringRemoveQuotes="true"   default: false
						Needed by mpi: mpirun -n 3 "program program_args" does NOT work
									   mpirun -n 3 program programargs    does work
				
				Path:
					The path to the executable is build as follows:
						<networkpath_root>/<from>path
					To local:
						<networkpath>/<from>
						is copied to
						<localPaths_enginesDir>/<to>
						where "<to>" is by default the same value of "<from>"
						When "<version" is defined, "_<version>" is added.
					Example:
						if:
						<networpath_root>        = /f/h4/opt
						<from> = <to>            = swan/lnx64
						<path>                   = bin/swan.exe
						<llocalPaths_enginesDir> = /tmp
						then:
						copyRecursive /f/h4/opt/swan/lnx64 /tmp/swan/lnx64
						all subdirs of /tmp/swan/lnx64 are added to the searchPaths automatically
				
				Environment parameters:
					type path:
						"." resolves to <localPaths_enginesDir>/<to>                (in example above: /tmp/swan/lnx64)
						example:
						<environment name="D3D_HOME" type="path">..\.</environment> (in example above: /tmp/swan)
					type raw:
						just the value
						example:
						<environment name="ARCH" type="raw">lnx64</environment>
				-->
  <programs>
    <program name="command_prompt" addSearchPaths="false">
      <path>cmd</path>
      <arguments>
        <argument>/C</argument>
      </arguments>
    </program>
    <program name="svn" addSearchPaths="false">
      <path>thirdparty\svn\win64\svn.exe</path>
    </program>
    <program name="DFlowFM" logOutputToFile="true">
      <location ref="dsctestbench-references" type="reference">
        <from>bin/dflowfm/win64</from>
      </location>
      <location ref="local" type="check">
        <from>teamcity_artifacts/bin/dflowfm/win64</from>
      </location>
      <path>dflowfm.exe</path>
      <arguments>
        <argument>--autostartstop</argument>
      </arguments>
      <environments>
        <environment name="OMP_NUM_THREADS" type="raw">1</environment>
      </environments>
    </program>
  </programs>
  <defaultTestCases>
    <testCase name="dflowfm_default">
      <location ref="dsctestbench-cases" type="input">
        <!-- if "to" is not specified, "from" is used as target -->
        <from>.</from>
      </location>
      <location ref="dsctestbench-references" type="reference">
        <from>win64</from>
      </location>
      <maxRunTime>3600.0</maxRunTime>
      <!-- seconds -->
    </testCase>
  </defaultTestCases>
      <testCases>
	    <testCase name="e02_f019_c013_tracer_channel3D" ref="dflowfm_default">
		  <path>e02_dflowfm/f019_transport/c013_tracer_channel3D</path>
		  <programs>
			<program ref="DFlowFM">
			  <arguments>
				<argument>tracer3D.mdu</argument>
				<argument>--autostartstop</argument>
			  </arguments>
			</program>
		  </programs>
		  <maxRunTime>15000.0000000</maxRunTime>
		  <checks>
			<file name="dflowfmoutput/tfl_his.nc" type="netCDF">
			  <parameters>
				<parameter name="waterlevel" toleranceAbsolute="0.0001" />
				<parameter name="x_velocity" toleranceAbsolute="0.0001" />
				<parameter name="y_velocity" toleranceAbsolute="0.0001" />
				<parameter name="salinity" toleranceAbsolute="0.0001" />
			  </parameters>
			</file>
			<file name="depthgr.xyz" ignore="true" />
		  </checks>
		</testCase>
		<testCase name="e02_f021_c001_bedwithobstacle_anticreep" ref="dflowfm_default">
		  <path>e02_dflowfm/f021_anti-creep/c001_bedwithobstacle_anticreep</path>
		  <programs>
			<program ref="DFlowFM">
			  <arguments>
				<argument>sigma.mdu</argument>
				<argument>--autostartstop</argument>
			  </arguments>
			</program>
		  </programs>
		  <maxRunTime>15000.0000000</maxRunTime>
		  <checks>
			<file name="dflowfmoutput/sigma_his.nc" type="netCDF">
			  <parameters>
				<parameter name="waterlevel" toleranceAbsolute="0.0001" />
				<parameter name="x_velocity" toleranceAbsolute="0.0001" />
				<parameter name="y_velocity" toleranceAbsolute="0.0001" />
				<parameter name="salinity" toleranceAbsolute="0.0001" />
			  </parameters>
			</file>
		  </checks>
		</testCase>
		<testCase name="e02_f021_c002_slopingbed_anticreep" ref="dflowfm_default">
		  <path>e02_dflowfm/f021_anti-creep/c002_slopingbed_anticreep</path>
		  <programs>
			<program ref="DFlowFM">
			  <arguments>
				<argument>anticreep01.mdu</argument>
				<argument>--autostartstop</argument>
			  </arguments>
			</program>
		  </programs>
		  <maxRunTime>15000.0000000</maxRunTime>
		  <checks>
			<file name="dflowfmoutput/anticreep01_his.nc" type="netCDF">
			  <parameters>
				<parameter name="waterlevel" toleranceAbsolute="0.0001" />
				<parameter name="x_velocity" toleranceAbsolute="0.0001" />
				<parameter name="y_velocity" toleranceAbsolute="0.0001" />
				<parameter name="salinity" toleranceAbsolute="0.0001" />
			  </parameters>
			</file>
		  </checks>
		</testCase>
     </testCases>
</deltaresTestbench_v3>
